export const ethSepoliaVaultManagerAddress="0x934213A3C381cc1Bfd0c9abb42049DE7B8FECFF4";

export const arbitrumSepoliaVaultManagerAddress="0x18584204aE38002e1369922e6B82d711aa38ae98";

export const vaultManagerAbi=[
{"type":"constructor","inputs":[{"name":"_usdPlnOracle","type":"address","internalType":"address"},
{"name":"_stabilskiToken","type":"address","internalType":"address"},
{"name":"_collateralManager","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},
{"type":"function","name":"collateralManager","inputs":[],
"outputs":[{"name":"","type":"address","internalType":"contract CollateralManagerInterface"}],"stateMutability":"view"},
{"type":"function","name":"depositCollateral",
"inputs":[{"name":"token","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"getAllBorrowers","inputs":[],"outputs":[{"name":"","type":"address[]","internalType":"address[]"}],
"stateMutability":"nonpayable"},
{"type":"function","name":"getCollateralValue","inputs":[{"name":"owner","type":"address","internalType":"address"},
{"name":"token","type":"address","internalType":"address"}],"outputs":[{"name":"inPLN","type":"uint256","internalType":"uint256"}],
"stateMutability":"view"},
{"type":"function","name":"getIsHealthyAfterWithdrawal",
"inputs":[{"name":"amount","type":"uint256","internalType":"uint256"},
    {"name":"token","type":"address","internalType":"address"}],
"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
{"type":"function","name":"getMaxBorrowableStabilskiTokens","inputs":[{"name":"owner","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"}],"outputs":[{"name":"amount","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"getVaultHealthFactor","inputs":[{"name":"vaultOwner","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"getVaultInfo","inputs":[{"name":"owner","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"}],"outputs":[{"name":"collateralAmount","type":"uint256","internalType":"uint256"},{"name":"debt","type":"uint256","internalType":"uint256"},{"name":"collateralToken","type":"address","internalType":"address"},{"name":"healthFactor","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"isLiquidatable","inputs":[{"name":"vaultOwner","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"}],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
{"type":"function","name":"liquidateVault","inputs":[{"name":"vaultOwner","type":"address","internalType":"address"},{"name":"token","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"mintPLST","inputs":[{"name":"collateralToken","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"function","name":"repayPLST","inputs":[{"name":"collateralToken","type":"address","internalType":"address"},{"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},{"type":"function","name":"stabilskiToken","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract StabilskiTokenInterface"}],"stateMutability":"view"},
{"type":"function","name":"usdPlnOracle","inputs":[],"outputs":[{"name":"","type":"address","internalType":"contract USDPLNOracleInterface"}],"stateMutability":"view"},
{"type":"function","name":"vaults","inputs":[{"name":"","type":"address","internalType":"address"},{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"collateralAmount","type":"uint256","internalType":"uint256"},{"name":"collateralTypeToken","type":"address","internalType":"address"},{"name":"debt","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
{"type":"function","name":"withdrawCollateral",
    "inputs":[{"name":"token","type":"address","internalType":"address"},
        {"name":"amount","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
{"type":"event","name":"CollateralDeposited",
    "inputs":[
        {"name":"vaultOwner","type":"address","indexed":false,"internalType":"address"},
        {"name":"token","type":"address","indexed":false,"internalType":"address"},
        {"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"CollateralWithdrawn",
    "inputs":[
        {"name":"vaultOwner","type":"address","indexed":false,"internalType":"address"},
        {"name":"token","type":"address","indexed":false,"internalType":"address"},
        {"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],
        "anonymous":false},
{"type":"event","name":"DebtRepaid",
    "inputs":[
        {"name":"vaultOwner","type":"address","indexed":false,"internalType":"address"},
        {"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"},
        {"name":"token","type":"address","indexed":false,"internalType":"address"}],
        "anonymous":false},
{"type":"event","name":"StabilskiTokenMinted","inputs":[{"name":"vaultOwner","type":"address","indexed":false,"internalType":"address"},{"name":"amount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"event","name":"VaultLiquidated","inputs":[{"name":"vaultOwner","type":"address","indexed":false,"internalType":"address"},{"name":"liquidator","type":"address","indexed":false,"internalType":"address"},{"name":"debtAmount","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"collateralAmount","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
{"type":"error","name":"AddressEmptyCode","inputs":[{"name":"target","type":"address","internalType":"address"}]},
{"type":"error","name":"AddressInsufficientBalance","inputs":[{"name":"account","type":"address","internalType":"address"}]},
{"type":"error","name":"FailedInnerCall","inputs":[]},
{"type":"error","name":"InvalidAllowance","inputs":[]},
{"type":"error","name":"InvalidCollateralToken","inputs":[]},
{"type":"error","name":"InvalidVault","inputs":[]},
{"type":"error","name":"LiquidatorCannotBeVaultOwner","inputs":[]},
{"type":"error","name":"NotEnoughCollateral","inputs":[]},
{"type":"error","name":"NotEnoughDebt","inputs":[]},
{"type":"error","name":"NotEnoughPLST","inputs":[]},
{"type":"error","name":"OverCollateralized","inputs":[]},
{"type":"error","name":"ReentrancyGuardReentrantCall","inputs":[]},
{"type":"error","name":"SafeERC20FailedOperation","inputs":[{"name":"token","type":"address","internalType":"address"}]},
{"type":"error","name":"UnderCollateralized","inputs":[]},
{"type":"error","name":"VaultAlreadyExists","inputs":[]}];