import type { Metadata } from "next";
import { Outfit
} from "next/font/google";
import "./globals.css";
import { Web3Provider } from "@/lib/Web3Provider";
import Navbar from "@/components/ui/Navbar";
import { Toaster } from "sonner";

const outfit = Outfit({
  variable: "--font-outfit",
  weight:['100', '200', '300', '500', '400', '600', '700', '800', '900'],
  style:["normal"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Stabilski.xyz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Web3Provider>
      <body
        className={`${outfit.variable} antialiased`}
        >
        <Navbar/>
        <Toaster style={{
          background:'red'
        }} />
       
        {children}
      </body>
      </Web3Provider>
    </html>
  );
}
